# Generated by Django 6.0 on 2026-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='主題'),
        ),
    ]
